import type { Pastel } from './types';

export const MOCK_PASTELES: Pastel[] = [
  // Chocolate
  {
    _id: '1',
    nombre: 'Chocolate Clásico',
    precio: 450,
    categoria: 'chocolate',
    imagen: '/images/catalogo/chocolate-clasico.jpg',
    disponible: true,
    descripcion: 'Nuestro Pastel de Chocolate Clásico es un bizcocho oscuro y esponjoso elaborado con cacao en polvo premium, con capas intercaladas de relleno de crema de chocolate brillante y una cobertura lisa con acabado elegante. Cada mordisco es una explosión de sabor intenso a chocolate con la suavidad perfecta del relleno.',
  },
  {
    _id: '2',
    nombre: 'Triple Chocolate',
    precio: 520,
    categoria: 'chocolate',
    imagen: '/images/catalogo/triple-chocolate.jpg',
    disponible: true,
    descripcion: 'Una experiencia chocolate extrema con tres capas intensas: chocolate oscuro, chocolate con leche y chocolate blanco. El ganache decorate cae lentamente por los bordes creando un efecto visuals impressionista. Perfecto para los verdadero amantes del chocolate.',
  },
  {
    _id: '3',
    nombre: 'Chocolate con Fresas',
    precio: 480,
    categoria: 'chocolate',
    imagen: '/images/catalogo/chocolate-fresas.jpg',
    disponible: true,
    descripcion: 'La combinación perfecta de lo intenso y lo fresco. Un bizcocho oscuro que contrasta elegantemente con fresas rojas frescas cortadas en láminas y crema blanca suave. Decorado con fresas enteras en la parte superior.',
  },
  {
    _id: '4',
    nombre: 'Lava de Chocolate',
    precio: 550,
    categoria: 'chocolate',
    imagen: '/images/catalogo/lava-chocolate.jpg',
    disponible: true,
    descripcion: 'El estrella de cualquier celebración. Con una consistencia firme en el exterior, al cortarlo revela un centro de chocolate líquido y brillante que fluye como lava. Una combinación de texturas que sorprende en cada bite.',
  },
  {
    _id: '5',
    nombre: 'Chocolate y Nueces',
    precio: 460,
    categoria: 'chocolate',
    imagen: '/images/catalogo/chocolate-nueces.jpg',
    disponible: true,
    descripcion: 'Para quienes aman la textura crujiente. Un bizcocho húmedo con trozos visibles de nuez caramelizada, cubierto con una capa rústica de chocolate con textura granular. El marriage perfecto entre lo suave y lo crocante.',
  },
  // Vainilla
  {
    _id: '6',
    nombre: 'Vainilla Clásico',
    precio: 380,
    categoria: 'vainilla',
    imagen: '/images/catalogo/vainilla-clasico.jpg',
    disponible: true,
    descripcion: 'La elegancia en su forma más pura. Un bizcocho claro, suave y esponjoso elaborado con esencia de vainilla natural, cubierto con crema blanca lisa y decoración sencilla con toques delicados. Un clásico que nunca pasa de moda.',
  },
  {
    _id: '7',
    nombre: 'Vainilla con Buttercream',
    precio: 420,
    categoria: 'vainilla',
    imagen: '/images/catalogo/vainilla-buttercream.jpg',
    disponible: true,
    descripcion: 'Capas esponjosas de bizcocho de vainilla coronadas por crema buttercream decorada en delicados espiraless. Cada capa es una nubes de textura sedosa que se deshace en tu boca. El favorito de los amantes de lo clásico.',
  },
  {
    _id: '8',
    nombre: 'Funfetti',
    precio: 440,
    categoria: 'vainilla',
    imagen: '/images/catalogo/funfetti.jpg',
    disponible: true,
    descripcion: 'Alegría pura en cada trozo. Un interior relleno de coloridas chispas de sprinkless que revelan un arcoíris al cortar. El exterior blanco con decoración ludique crea un pastel perfecto para celebraciones alegres y niños.',
  },
  {
    _id: '9',
    nombre: 'Vainilla con Caramelo',
    precio: 460,
    categoria: 'vainilla',
    imagen: '/images/catalogo/vainilla-caramelo.jpg',
    disponible: true,
    descripcion: 'Un bizcocho de vainilla dorada con capas de caramelo líquido que gotea elegantemente por los lados. La combinación dulce y cremosa crea un contraste visual y de sabores irresistible. Decorado con piezas de caramelo crujiente.',
  },
  {
    _id: '10',
    nombre: 'Vainilla y Almendras',
    precio: 440,
    categoria: 'vainilla',
    imagen: '/images/catalogo/vainilla-almendras.jpg',
    disponible: true,
    descripcion: 'Sofisticación en cada detalle. Trozos de almendra tostada distribuidos por todo el bizcocho, coronado con láminas de almendra doradas en la parte superior. Una textura crujiente que complementa la suavidad de la vainilla premium.',
  },
  // Frutas
  {
    _id: '11',
    nombre: 'Fresa',
    precio: 420,
    categoria: 'frutas',
    imagen: '/images/catalogo/fresa.jpg',
    disponible: true,
    descripcion: 'Romanticismo en forma de pastel. Un tono rosado suave achieved through puré de fresas naturales, decorado con fresas frescas enteras y medioambollones. La frescura de la fruta combina perfectamente con la crema batida suave.',
  },
  {
    _id: '12',
    nombre: 'Piña',
    precio: 400,
    categoria: 'frutas',
    imagen: '/images/catalogo/pina.jpg',
    disponible: true,
    descripcion: 'Un toque tropical que transporta a días soleados. Rodajas de piña dorada dispuestas en corona, con brillo de caramelo que refleja la luz. El jugo de piña natural moistens el bizcocho creando una experiencia húmeda y jugosa.',
  },
  {
    _id: '13',
    nombre: 'Mango',
    precio: 440,
    categoria: 'frutas',
    imagen: '/images/catalogo/mango.jpg',
    disponible: true,
    descripcion: 'Vibrante y tropical. Un color amarillo achieved through puré de mango maduro, con capas de crema y pulpa de mango. La sweetness natural de la fruta brilla sin necesidad de sabores artificiales. Un explode de verano en cada mordida.',
  },
  {
    _id: '14',
    nombre: 'Frutos Rojos',
    precio: 480,
    categoria: 'frutas',
    imagen: '/images/catalogo/frutos-rojos.jpg',
    disponible: true,
    descripcion: 'La combinación de berries más deliciosa. Decorado con una corona de moras, frambuesas y arándanos frescos sobre crema blanca. El contraste entre el blanco de la crema y los colores intensos de las frutas crea un postre tan hermoso como delicioso.',
  },
  {
    _id: '15',
    nombre: 'Manzana',
    precio: 390,
    categoria: 'frutas',
    imagen: '/images/catalogo/manzana.jpg',
    disponible: true,
    descripcion: 'Un abrazo de cosecha. Trozos de manzana caramelizada visibles en cada corte, con un delicado toque de canela que perfuma el ambiente. El color dorado del bizcocho y las piezas de fruta crean un aspecto casero y reconfortante.',
  },
];

export const MOCK_CATEGORIAS = ['todos', 'chocolate', 'vainilla', 'frutas'];